import React from 'react';
import { createRoot } from 'react-dom/client';
import { MemoryRouter, Route, Routes, Link } from 'react-router-dom';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { VenueIntegrationsPanel } from '../../../src/components/venue/VenueIntegrationsPanel';
import { VenueAddressRequests } from '../../../src/components/admin/VenueAddressRequests';
import { confirmPreview } from './stub';
import '../../../src/index.css';
confirmPreview();
const query=new QueryClient({defaultOptions:{queries:{retry:false}}});
createRoot(document.getElementById('root')!).render(<React.StrictMode><QueryClientProvider client={query}><MemoryRouter><div className="min-h-screen bg-background text-foreground"><aside className="flex flex-wrap gap-4 border-b bg-muted p-3 text-xs"><span>Local fixture · no live domains or accounts</span><Link to="/">Venue owner</Link><Link to="/admin">PULSE admin</Link><button onClick={()=>{sessionStorage.removeItem('venue-address-preview');location.reload();}}>Reset fixture</button></aside><main className="mx-auto max-w-3xl space-y-5 px-4 py-6"><h1 className="text-2xl font-semibold">Venue integrations</h1><p className="text-sm text-muted-foreground">Pickleball Palace</p><Routes><Route path="/" element={<VenueIntegrationsPanel venueId="10000000-0000-4000-8000-000000000001" groupId="community" canManageCommunity />} /><Route path="/admin" element={<VenueAddressRequests />} /><Route path="*" element={<p>Prerequisite settings destination · fixture</p>} /></Routes></main></div></MemoryRouter></QueryClientProvider></React.StrictMode>);
