import { useState } from "react";
import { Lock, Copy, Check, Share2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { toast } from "sonner";
import { cn } from "@/lib/utils";

interface InviteCodeCardProps {
  /** The XYZ-ABCD invite code generated by the DB trigger. */
  code: string;
  /** Event id — used to build a deep-link the host can share. */
  eventId: string;
  /** Optional event name — included in the Web Share API payload. */
  eventName?: string;
  className?: string;
}

/**
 * Host-side invite-code share card.
 *
 * Surfaces the auto-generated code in the host's detail page hero so
 * they can copy it (or use the OS share sheet) without hunting through
 * settings dialogs. The code is the primary brand-distinctive element
 * here — large, tabular, gold-tinted — and the helper buttons sit
 * underneath.
 *
 * Phase 5 will fold this into a richer "People" tab once the host UI
 * overhaul lands. For now it stands alone so Phase 3 ships a complete
 * loop: create invite-only event → see code → share code.
 */
export function InviteCodeCard({ code, eventId, eventName, className }: InviteCodeCardProps) {
  const [copied, setCopied] = useState(false);

  // Deep link players can open to land directly on the join confirmation.
  // Phase 4 wires up the ?invite=… search-param consumer.
  const joinUrl = `${window.location.origin}/round-robin?invite=${encodeURIComponent(code)}`;

  const handleCopyCode = async () => {
    try {
      await navigator.clipboard.writeText(code);
      setCopied(true);
      toast.success("Invite code copied");
      setTimeout(() => setCopied(false), 1800);
    } catch {
      toast.error("Could not copy — try selecting it manually");
    }
  };

  const handleShare = async () => {
    const shareText = eventName
      ? `Join "${eventName}" on PULSE — invite code ${code}`
      : `Join my Round Robin on PULSE — invite code ${code}`;

    if (typeof navigator !== "undefined" && (navigator as Navigator & { share?: (d: ShareData) => Promise<void> }).share) {
      try {
        await (navigator as Navigator & { share: (d: ShareData) => Promise<void> }).share({
          title: eventName || "PULSE Round Robin",
          text: shareText,
          url: joinUrl,
        });
        return;
      } catch {
        // User cancelled or share failed — fall through to clipboard.
      }
    }

    try {
      await navigator.clipboard.writeText(`${shareText}\n${joinUrl}`);
      toast.success("Share text copied to clipboard");
    } catch {
      toast.error("Could not copy share text");
    }
  };

  return (
    <div
      className={cn(
        "relative rounded-2xl border border-primary/20 bg-gradient-to-br from-primary/[0.05] via-card to-primary/[0.03]",
        "p-4 sm:p-5",
        className,
      )}
    >
      <div className="flex items-start justify-between gap-3 mb-3">
        <div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-wider text-muted-foreground">
          <Lock className="h-3.5 w-3.5 text-primary" />
          Invite-only · Share to join
        </div>
      </div>

      <button
        type="button"
        onClick={handleCopyCode}
        className={cn(
          "w-full font-mono text-2xl sm:text-3xl font-bold tracking-[0.2em] tabular-nums",
          "text-primary py-3 px-2 rounded-xl",
          "bg-primary/10 hover:bg-primary/15 active:scale-[0.99] transition-all",
          "border border-primary/15",
        )}
        aria-label={`Invite code ${code} — tap to copy`}
      >
        {code}
      </button>

      <div className="flex items-center gap-2 mt-3">
        <Button
          variant="outline"
          size="sm"
          onClick={handleCopyCode}
          className="flex-1 gap-1.5"
        >
          {copied ? (
            <>
              <Check className="h-3.5 w-3.5" />
              Copied
            </>
          ) : (
            <>
              <Copy className="h-3.5 w-3.5" />
              Copy code
            </>
          )}
        </Button>
        <Button
          variant="default"
          size="sm"
          onClick={handleShare}
          className="flex-1 gap-1.5"
        >
          <Share2 className="h-3.5 w-3.5" />
          Share
        </Button>
      </div>
    </div>
  );
}
