-- ============ Phase 1: RR invite codes ============
ALTER TABLE public.round_robin_events
  ADD COLUMN IF NOT EXISTS invite_code VARCHAR(9) UNIQUE;

COMMENT ON COLUMN public.round_robin_events.invite_code IS
  'Short alphanumeric code (XYZ-ABCD format) for invite-only events. Auto-generated by trigger when registration_mode = ''invite_only''.';

CREATE OR REPLACE FUNCTION public.generate_rr_invite_code()
RETURNS TEXT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_alphabet   TEXT    := 'ABCDEFGHJKMNPQRSTUVWXYZ23456789';
  v_alpha_len  INTEGER := length(v_alphabet);
  v_code       TEXT;
  v_i          INTEGER;
  v_attempts   INTEGER := 0;
BEGIN
  LOOP
    v_code := '';
    FOR v_i IN 1..3 LOOP
      v_code := v_code || substr(v_alphabet, 1 + floor(random() * v_alpha_len)::INT, 1);
    END LOOP;
    v_code := v_code || '-';
    FOR v_i IN 1..4 LOOP
      v_code := v_code || substr(v_alphabet, 1 + floor(random() * v_alpha_len)::INT, 1);
    END LOOP;
    IF NOT EXISTS (SELECT 1 FROM public.round_robin_events WHERE invite_code = v_code) THEN
      RETURN v_code;
    END IF;
    v_attempts := v_attempts + 1;
    IF v_attempts > 50 THEN
      RAISE EXCEPTION 'Could not generate unique invite code after 50 attempts';
    END IF;
  END LOOP;
END;
$$;

GRANT EXECUTE ON FUNCTION public.generate_rr_invite_code() TO authenticated, service_role;

CREATE OR REPLACE FUNCTION public.rr_events_set_invite_code()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NEW.registration_mode = 'invite_only'
     AND NEW.invite_code IS NULL
     AND (TG_OP = 'INSERT' OR NEW.registration_mode IS DISTINCT FROM OLD.registration_mode)
  THEN
    NEW.invite_code := public.generate_rr_invite_code();
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS rr_events_invite_code_trigger ON public.round_robin_events;
DROP TRIGGER IF EXISTS rr_events_set_invite_code ON public.round_robin_events;
CREATE TRIGGER rr_events_set_invite_code
  BEFORE INSERT OR UPDATE OF registration_mode
  ON public.round_robin_events
  FOR EACH ROW
  EXECUTE FUNCTION public.rr_events_set_invite_code();

CREATE OR REPLACE FUNCTION public.preview_round_robin_by_code(p_code TEXT)
RETURNS TABLE(
  event_id              UUID,
  event_name            TEXT,
  event_date            DATE,
  event_start_time      TEXT,
  event_status          public.round_robin_status,
  num_courts            INT,
  num_rounds            INT,
  current_players       INT,
  max_players           INT,
  registration_deadline TIMESTAMPTZ,
  organizer_name        TEXT,
  organizer_avatar_url  TEXT,
  already_joined        BOOLEAN
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_event   RECORD;
  v_count   INT;
  v_user_id UUID := auth.uid();
  v_joined  BOOLEAN := false;
BEGIN
  p_code := upper(trim(p_code));
  SELECT * INTO v_event FROM public.round_robin_events WHERE invite_code = p_code LIMIT 1;
  IF NOT FOUND THEN RAISE EXCEPTION 'Invalid invite code' USING ERRCODE = '02000'; END IF;
  SELECT count(*)::INT INTO v_count FROM public.round_robin_players rrp WHERE rrp.event_id = v_event.id AND rrp.active = true;
  IF v_user_id IS NOT NULL THEN
    SELECT EXISTS (SELECT 1 FROM public.round_robin_players rrp WHERE rrp.event_id = v_event.id AND rrp.player_id = v_user_id AND rrp.active = true) INTO v_joined;
  END IF;
  RETURN QUERY SELECT
    v_event.id, v_event.name, v_event.date, v_event.start_time::TEXT, v_event.status,
    v_event.num_courts, v_event.num_rounds, v_count, v_event.max_players, v_event.registration_deadline,
    (SELECT COALESCE(p.display_name, p.full_name, 'Organizer') FROM public.profiles p WHERE p.id = v_event.organizer_id)::TEXT,
    (SELECT p.avatar_url FROM public.profiles p WHERE p.id = v_event.organizer_id)::TEXT,
    v_joined;
END;
$$;

GRANT EXECUTE ON FUNCTION public.preview_round_robin_by_code(TEXT) TO authenticated;

-- join_round_robin_by_code (hardened version from Phase 3 directly)
CREATE OR REPLACE FUNCTION public.join_round_robin_by_code(p_code TEXT)
RETURNS TABLE(event_id UUID, registration_status TEXT, message TEXT)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_event           RECORD;
  v_user_id         UUID := auth.uid();
  v_confirmed_count INT;
  v_max_players     INT;
  v_status          TEXT;
  v_existing        RECORD;
BEGIN
  IF v_user_id IS NULL THEN RAISE EXCEPTION 'Authentication required to join' USING ERRCODE = '42501'; END IF;
  p_code := upper(trim(p_code));
  SELECT id, status, max_players, registration_deadline, registration_mode, name
    INTO v_event FROM public.round_robin_events WHERE invite_code = p_code FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Invalid invite code' USING ERRCODE = '02000'; END IF;
  IF v_event.status = 'completed' OR v_event.status = 'voided' THEN
    RAISE EXCEPTION 'This event is no longer accepting players' USING ERRCODE = '22023';
  END IF;
  IF v_event.registration_deadline IS NOT NULL AND now() > v_event.registration_deadline THEN
    RAISE EXCEPTION 'Registration has closed for this event' USING ERRCODE = '22023';
  END IF;
  SELECT id, active, registration_status INTO v_existing FROM public.round_robin_players
    WHERE round_robin_players.event_id = v_event.id AND round_robin_players.player_id = v_user_id LIMIT 1;
  IF FOUND AND v_existing.active = true THEN
    RETURN QUERY SELECT v_event.id, COALESCE(v_existing.registration_status, 'confirmed'), 'You''re already registered for this event'::TEXT;
    RETURN;
  END IF;
  v_max_players := v_event.max_players;
  IF v_max_players IS NOT NULL THEN
    SELECT count(*)::INT INTO v_confirmed_count FROM public.round_robin_players
      WHERE round_robin_players.event_id = v_event.id AND round_robin_players.active = true
        AND COALESCE(registration_status, 'confirmed') = 'confirmed';
    IF v_confirmed_count >= v_max_players THEN v_status := 'waitlisted'; ELSE v_status := 'confirmed'; END IF;
  ELSE
    v_status := 'confirmed';
  END IF;
  IF v_event.registration_deadline IS NOT NULL AND now() > v_event.registration_deadline THEN
    RAISE EXCEPTION 'Registration has closed for this event' USING ERRCODE = '22023';
  END IF;
  IF FOUND THEN
    UPDATE public.round_robin_players SET active = true, registration_status = v_status, joined_at = now() WHERE id = v_existing.id;
  ELSE
    INSERT INTO public.round_robin_players (event_id, player_id, active, registration_status, joined_at)
    VALUES (v_event.id, v_user_id, true, v_status, now());
  END IF;
  RETURN QUERY SELECT v_event.id, v_status,
    CASE WHEN v_status = 'waitlisted' THEN 'Event is full — you''re on the waitlist'
         ELSE 'You''re in. See you on the court.' END::TEXT;
END;
$$;

GRANT EXECUTE ON FUNCTION public.join_round_robin_by_code(TEXT) TO authenticated;

-- ============ Phase 2: Score pipeline ============
ALTER TABLE public.matches
  ADD COLUMN IF NOT EXISTS count_for_rating BOOLEAN DEFAULT true;

COMMENT ON COLUMN public.matches.count_for_rating IS
  'When false, the match is visible in match history but excluded from rating calculations.';

UPDATE public.matches m
   SET count_for_rating = false
  FROM public.round_robin_schedule s
  JOIN public.round_robin_events e ON e.id = s.event_id
 WHERE s.match_id = m.id
   AND e.rating_eligible = false
   AND m.count_for_rating IS DISTINCT FROM false;

CREATE OR REPLACE FUNCTION public.recalculate_all_ratings()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
  match_record    RECORD;
  player_record   RECORD;
  p1_id UUID; p2_id UUID; p3_id UUID; p4_id UUID;
  p1_rating NUMERIC; p2_rating NUMERIC; p3_rating NUMERIC; p4_rating NUMERIC;
  p1_matches INTEGER; p2_matches INTEGER; p3_matches INTEGER; p4_matches INTEGER;
  v_rating_change NUMERIC;
  current_week    DATE;
BEGIN
  current_week := get_week_start(CURRENT_DATE);
  UPDATE profiles SET current_rating = 3.00, week_start_rating = 3.00, week_start_date = current_week WHERE id IS NOT NULL;
  FOR match_record IN
    SELECT m.id AS match_id, m.match_date, m.team1_score, m.team2_score, m.match_type, m.week_start, m.created_at,
           array_agg(mp.player_id ORDER BY mp.team, mp.id) AS player_ids,
           array_agg(mp.team ORDER BY mp.team, mp.id) AS teams
    FROM matches m JOIN match_participants mp ON mp.match_id = m.id
    WHERE m.status = 'approved' AND COALESCE(m.voided, false) = false AND COALESCE(m.count_for_rating, true) = true
    GROUP BY m.id, m.match_date, m.team1_score, m.team2_score, m.match_type, m.week_start, m.created_at
    HAVING COUNT(*) = 4
    ORDER BY m.match_date, m.created_at, m.id
  LOOP
    p1_id := match_record.player_ids[1]; p2_id := match_record.player_ids[2];
    p3_id := match_record.player_ids[3]; p4_id := match_record.player_ids[4];
    SELECT COALESCE((SELECT mp_sub.rating_after FROM match_participants mp_sub JOIN matches m_sub ON mp_sub.match_id = m_sub.id
      WHERE mp_sub.player_id = p1_id AND m_sub.status = 'approved'
        AND COALESCE(m_sub.voided, false) = false AND COALESCE(m_sub.count_for_rating, true) = true
        AND (m_sub.match_date < match_record.match_date OR (m_sub.match_date = match_record.match_date AND m_sub.created_at < match_record.created_at)
             OR (m_sub.match_date = match_record.match_date AND m_sub.created_at = match_record.created_at AND m_sub.id < match_record.match_id))
      ORDER BY m_sub.match_date DESC, m_sub.created_at DESC, m_sub.id DESC LIMIT 1), 3.00), p.total_matches
    INTO p1_rating, p1_matches FROM profiles p WHERE p.id = p1_id;
    SELECT COALESCE((SELECT mp_sub.rating_after FROM match_participants mp_sub JOIN matches m_sub ON mp_sub.match_id = m_sub.id
      WHERE mp_sub.player_id = p2_id AND m_sub.status = 'approved'
        AND COALESCE(m_sub.voided, false) = false AND COALESCE(m_sub.count_for_rating, true) = true
        AND (m_sub.match_date < match_record.match_date OR (m_sub.match_date = match_record.match_date AND m_sub.created_at < match_record.created_at)
             OR (m_sub.match_date = match_record.match_date AND m_sub.created_at = match_record.created_at AND m_sub.id < match_record.match_id))
      ORDER BY m_sub.match_date DESC, m_sub.created_at DESC, m_sub.id DESC LIMIT 1), 3.00), p.total_matches
    INTO p2_rating, p2_matches FROM profiles p WHERE p.id = p2_id;
    SELECT COALESCE((SELECT mp_sub.rating_after FROM match_participants mp_sub JOIN matches m_sub ON mp_sub.match_id = m_sub.id
      WHERE mp_sub.player_id = p3_id AND m_sub.status = 'approved'
        AND COALESCE(m_sub.voided, false) = false AND COALESCE(m_sub.count_for_rating, true) = true
        AND (m_sub.match_date < match_record.match_date OR (m_sub.match_date = match_record.match_date AND m_sub.created_at < match_record.created_at)
             OR (m_sub.match_date = match_record.match_date AND m_sub.created_at = match_record.created_at AND m_sub.id < match_record.match_id))
      ORDER BY m_sub.match_date DESC, m_sub.created_at DESC, m_sub.id DESC LIMIT 1), 3.00), p.total_matches
    INTO p3_rating, p3_matches FROM profiles p WHERE p.id = p3_id;
    SELECT COALESCE((SELECT mp_sub.rating_after FROM match_participants mp_sub JOIN matches m_sub ON mp_sub.match_id = m_sub.id
      WHERE mp_sub.player_id = p4_id AND m_sub.status = 'approved'
        AND COALESCE(m_sub.voided, false) = false AND COALESCE(m_sub.count_for_rating, true) = true
        AND (m_sub.match_date < match_record.match_date OR (m_sub.match_date = match_record.match_date AND m_sub.created_at < match_record.created_at)
             OR (m_sub.match_date = match_record.match_date AND m_sub.created_at = match_record.created_at AND m_sub.id < match_record.match_id))
      ORDER BY m_sub.match_date DESC, m_sub.created_at DESC, m_sub.id DESC LIMIT 1), 3.00), p.total_matches
    INTO p4_rating, p4_matches FROM profiles p WHERE p.id = p4_id;
    v_rating_change := calculate_pulse_rating_change(p1_rating, p2_rating, p3_rating, p4_rating,
      match_record.team1_score, match_record.team2_score, match_record.team1_score > match_record.team2_score,
      match_record.match_type, p1_matches);
    UPDATE match_participants SET rating_before = p1_rating, rating_after = p1_rating + v_rating_change, rating_change = v_rating_change
      WHERE match_id = match_record.match_id AND player_id = p1_id;
    UPDATE match_participants SET rating_before = p2_rating, rating_after = p2_rating + v_rating_change, rating_change = v_rating_change
      WHERE match_id = match_record.match_id AND player_id = p2_id;
    UPDATE match_participants SET rating_before = p3_rating, rating_after = p3_rating - v_rating_change, rating_change = -v_rating_change
      WHERE match_id = match_record.match_id AND player_id = p3_id;
    UPDATE match_participants SET rating_before = p4_rating, rating_after = p4_rating - v_rating_change, rating_change = -v_rating_change
      WHERE match_id = match_record.match_id AND player_id = p4_id;
    UPDATE profiles SET current_rating = p1_rating + v_rating_change WHERE id = p1_id;
    UPDATE profiles SET current_rating = p2_rating + v_rating_change WHERE id = p2_id;
    UPDATE profiles SET current_rating = p3_rating - v_rating_change WHERE id = p3_id;
    UPDATE profiles SET current_rating = p4_rating - v_rating_change WHERE id = p4_id;
  END LOOP;
  FOR player_record IN SELECT id FROM profiles LOOP
    UPDATE profiles SET week_start_rating = COALESCE(
      (SELECT mp_sub.rating_after FROM match_participants mp_sub JOIN matches m_sub ON mp_sub.match_id = m_sub.id
        WHERE mp_sub.player_id = player_record.id AND m_sub.status = 'approved'
          AND COALESCE(m_sub.voided, false) = false AND COALESCE(m_sub.count_for_rating, true) = true
          AND m_sub.week_start < current_week
        ORDER BY m_sub.match_date DESC, m_sub.created_at DESC, m_sub.id DESC LIMIT 1), 3.00),
      week_start_date = current_week WHERE id = player_record.id;
  END LOOP;
  PERFORM recalculate_all_player_stats();
END;
$function$;

-- submit_rr_match_score (hardened version w/ FOR UPDATE lock)
CREATE OR REPLACE FUNCTION public.submit_rr_match_score(
  p_schedule_id  UUID,
  p_team1_score  INT,
  p_team2_score  INT
)
RETURNS UUID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
  v_schedule         RECORD;
  v_event            RECORD;
  v_user_id          UUID := auth.uid();
  v_match_id         UUID;
  v_court_id         UUID;
  v_count_for_rating BOOLEAN;
  v_participant_ids  UUID[];
BEGIN
  IF v_user_id IS NULL THEN RAISE EXCEPTION 'Authentication required' USING ERRCODE = '42501'; END IF;
  SELECT * INTO v_schedule FROM round_robin_schedule WHERE id = p_schedule_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Schedule row not found' USING ERRCODE = '02000'; END IF;
  IF v_schedule.is_bye THEN RAISE EXCEPTION 'Cannot submit a score for a bye match'; END IF;
  SELECT * INTO v_event FROM round_robin_events WHERE id = v_schedule.event_id;
  IF NOT FOUND THEN RAISE EXCEPTION 'Parent event not found'; END IF;
  IF v_event.organizer_id <> v_user_id AND NOT public.has_role(v_user_id, 'admin'::app_role) THEN
    RAISE EXCEPTION 'Not authorized to submit scores for this event' USING ERRCODE = '42501';
  END IF;
  IF v_schedule.a1_player_id IS NULL OR v_schedule.a2_player_id IS NULL
     OR v_schedule.b1_player_id IS NULL OR v_schedule.b2_player_id IS NULL THEN
    RAISE EXCEPTION 'Match has unfilled player slots; cannot submit score';
  END IF;
  v_count_for_rating := COALESCE(v_event.rating_eligible, true);
  IF v_event.location IS NOT NULL THEN
    BEGIN
      v_court_id := v_event.location::UUID;
    EXCEPTION WHEN invalid_text_representation THEN
      SELECT id INTO v_court_id FROM courts WHERE name = v_event.location LIMIT 1;
    END;
  END IF;
  UPDATE round_robin_schedule SET team1_score = p_team1_score, team2_score = p_team2_score WHERE id = p_schedule_id;
  v_participant_ids := ARRAY[v_schedule.a1_player_id, v_schedule.a2_player_id, v_schedule.b1_player_id, v_schedule.b2_player_id];
  IF v_schedule.match_id IS NOT NULL THEN
    UPDATE matches
       SET team1_score = p_team1_score, team2_score = p_team2_score, verified_by = v_participant_ids,
           court_id = v_court_id,
           other_location = CASE WHEN v_court_id IS NULL THEN v_event.location ELSE NULL END,
           count_for_rating = v_count_for_rating
     WHERE id = v_schedule.match_id;
    v_match_id := v_schedule.match_id;
  ELSE
    INSERT INTO matches (match_date, team1_score, team2_score, created_by, source, round_no, court_no,
      court_id, other_location, match_type, status, verified_by, count_for_rating)
    VALUES (v_event.date, p_team1_score, p_team2_score, v_user_id, 'round_robin', v_schedule.round_no, v_schedule.court_no,
      v_court_id, CASE WHEN v_court_id IS NULL THEN v_event.location ELSE NULL END,
      v_event.rating_type::TEXT, 'approved', v_participant_ids, v_count_for_rating)
    RETURNING id INTO v_match_id;
    INSERT INTO match_participants (match_id, player_id, team) VALUES
      (v_match_id, v_schedule.a1_player_id, 1),
      (v_match_id, v_schedule.a2_player_id, 1),
      (v_match_id, v_schedule.b1_player_id, 2),
      (v_match_id, v_schedule.b2_player_id, 2);
    UPDATE round_robin_schedule SET match_id = v_match_id WHERE id = p_schedule_id;
  END IF;
  INSERT INTO round_robin_audit (event_id, editor_id, change_type, changes, reason)
  VALUES (v_event.id, v_user_id, 'score_submit',
    jsonb_build_object('schedule_id', p_schedule_id, 'match_id', v_match_id,
      'team1_score', p_team1_score, 'team2_score', p_team2_score, 'count_for_rating', v_count_for_rating),
    'Score submitted for Round ' || v_schedule.round_no || ', Court ' || v_schedule.court_no);
  RETURN v_match_id;
END;
$$;

GRANT EXECUTE ON FUNCTION public.submit_rr_match_score(UUID, INT, INT) TO authenticated;

SELECT public.recalculate_all_ratings();