// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { createSafeAuthStorage, getSupabaseAuthStorageKey } from '@/lib/supabaseAuthStorage';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const SUPABASE_PROJECT_ID = import.meta.env.VITE_SUPABASE_PROJECT_ID;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: createSafeAuthStorage(),
    persistSession: true,
    autoRefreshToken: true,
    // Never reuse a JWT across Supabase projects. During a backend cutover a
    // shared key causes the old project's token to be sent to the new issuer,
    // producing repeated bad_jwt responses and an auth/dashboard flash loop.
    storageKey: getSupabaseAuthStorageKey(SUPABASE_PROJECT_ID, SUPABASE_URL),
    flowType: 'pkce',
  }
});
